name: aged-stage
spring:
  profiles:
    active: dev
---
spring:
  profiles: dev
  datasource:
#    url: jdbc:mysql://42.192.42.199:3306/aged-stage-put?useUnicode=true&characterEncoding=utf-8&useSSL=false&tcpRcvBuf=1024000&autoReconnect=true&failOverReadOnly=false&connectTimeout=0&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai
#    userName: aged-stage-put
#    password: 1111
     url: jdbc:mysql://127.0.0.1:3306/aged-stage-put?useUnicode=true&characterEncoding=utf-8&useSSL=false&tcpRcvBuf=1024000&autoReconnect=true&failOverReadOnly=false&connectTimeout=0&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai
     userName: ENC(TBl10oYkYENENdk3WeJwdQ==)
     password: ENC(gV3vhiS57cpJ3rqTdztsgQ==)
  redis:
#    host: 42.193.17.167
    host: 127.0.0.1
#    port: 6301
    port: 6379
    password:
    timeout: 120000
    readTimeout: 120000
    database: 5
    jedis:
      pool:
        min-idle: 8
        max-idle: 500
        max-active: 2000
        max-wait: 60000
locationTemp: /Users/singer/data #上传文件的临时目录
jasypt:
    encryptor:
      password: sss1111

